name: AutoWorldRegen
version: 1.0
main: com.autoregen.AutoWorldRegen
api-version: 1.21
author: Hyluna
description: Auto-regenerates world chunks while protecting claims and active players
softdepend: [GriefPrevention]

commands:
  autoregen:
    description: Main plugin command
    usage: /autoregen [now|reload|status]
    permission: autoregen.admin

permissions:
  autoregen.admin:
    description: Allow access to autoregen commands
    default: op
